import {prompts,categories} from './data.js';import {store} from './storage.js';
const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}
const app=document.querySelector('#app');let route='home',query='',cat='All';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const user=tg?.initDataUnsafe?.user;
function header(){return `<header class="header"><button class="icon" onclick="openDrawer()">☰</button><div class="brand">✨ AI Prompt Vault</div><button class="icon" onclick="go('search')">⌕</button></header>`}
function nav(){return `<div class="bottom"><nav class="nav"><button class="${route==='home'?'active':''}" onclick="go('home')"><span>⌂</span>Home</button><button class="${route==='search'?'active':''}" onclick="go('search')"><span>⌕</span>Explore</button><button class="${route==='favorites'?'active':''}" onclick="go('favorites')"><span>♥</span>Saved</button><button class="${route==='history'?'active':''}" onclick="go('history')"><span>◷</span>History</button><button class="${route==='profile'?'active':''}" onclick="go('profile')"><span>●</span>Profile</button></nav></div>`}
function card(p){const fav=store.favorites().includes(p.id);return `<article class="card" onclick="openPrompt('${p.id}')"><div class="thumbwrap"><img class="thumb" src="${p.image}" alt="${esc(p.title)}"><button class="favorite-btn" onclick="event.stopPropagation();toggleFav('${p.id}')" aria-label="Favorite">${fav?'♥':'♡'}</button></div><div class="cardbody"><div class="title">${esc(p.title)}</div><div class="meta">${p.category.slice(0,2).map(esc).join(' • ')}</div>${p.premium?'<span class="badge">👑 Premium</span>':''}</div></article>`}
let visibleCount=5;let lastListKey='';
function resetPagination(key){if(lastListKey!==key){lastListKey=key;visibleCount=5}}
function loadMore(){visibleCount+=3;render()}
function moreButton(list){return visibleCount<list.length?`<button class="btn secondary" style="width:100%;margin-top:14px" onclick="loadMore()">Load 3 more</button>`:''}
function filteredSearch(){return prompts.filter(p=>(cat==='All'||p.category.includes(cat))&&(p.title+' '+p.tags.join(' ')).toLowerCase().includes(query.toLowerCase()))}
function home(){let list=cat==='All'?prompts:prompts.filter(p=>p.category.includes(cat));resetPagination('home|'+cat);let shown=list.slice(0,visibleCount);return `<section class="page"><div class="hero"><div class="muted">Premium AI prompt collection</div><h1>Create better with ready-to-use prompts.</h1><p class="muted">Browse, save and unlock prompts. Favorites and history stay in your browser.</p></div><div class="chips">${categories.map(x=>`<button class="chip ${cat===x?'active':''}" onclick="filterCat('${x}')">${x}</button>`).join('')}</div><div class="sectionhead"><h2>🔥 ${cat==='All'?'Trending Today':esc(cat)}</h2></div><div class="grid">${shown.map(card).join('')||'<p class="muted">No posts in this category.</p>'}</div>${moreButton(list)}</section>`}
function searchPage(){let list=filteredSearch();resetPagination('search|'+cat+'|'+query);let shown=list.slice(0,visibleCount);return `<section class="page"><h2>🔍 Explore</h2><input class="search" placeholder="Search AI prompts..." value="${esc(query)}" oninput="search(this.value)"><div class="chips">${categories.map(x=>`<button class="chip ${cat===x?'active':''}" onclick="filterCat('${x}')">${x}</button>`).join('')}</div><div class="grid">${shown.map(card).join('')||'<p class="muted">No prompts found.</p>'}</div>${moreButton(list)}</section>`}
function details(id){let p=prompts.find(x=>x.id===id);if(!p)return '<section class="page"><p>Prompt not found.</p></section>';store.addHistory(id);let unlocked=store.unlocked().includes(id);return `<section class="page detail"><button class="btn secondary" onclick="goBack()">← Back</button><div style="height:12px"></div><img src="${p.image}" alt="${esc(p.title)}"><h1>${esc(p.title)}</h1><div class="meta">⭐ ${p.rating} · ${p.uses} Uses · ${p.category.join(' • ')}</div><p class="muted">${esc(p.description)}</p><div class="tags">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>${p.premium&&!unlocked?`<div class="lock"><h3>🔐 Premium Prompt Locked</h3><p class="muted">Complete the demo unlock step to reveal this prompt.</p><div class="progress"><i style="width:0%"></i></div><button class="btn" onclick="unlockPrompt('${p.id}')">▶ Watch Ad to Unlock</button></div>`:`<div class="lock"><h3>📋 Full Prompt</h3><p>${esc(p.prompt)}</p><div class="actions"><button class="btn" onclick="copyPrompt('${p.id}')">📋 Copy Prompt</button><button class="btn secondary" onclick="downloadPrompt('${p.id}')">⬇ Download TXT</button><button class="btn secondary" onclick="toggleFav('${p.id}')">♥ ${store.favorites().includes(p.id)?'Saved':'Save'}</button><a class="btn secondary" href="${p.youtube}" target="_blank" rel="noopener">▶ YouTube Guide</a></div></div>`}</section>`}
function favorites(){let a=store.favorites();return `<section class="page"><h2>❤️ Favorites</h2><div class="grid">${prompts.filter(p=>a.includes(p.id)).map(card).join('')||'<p class="muted">No saved prompts yet.</p>'}</div></section>`}
function historyPage(){let a=store.history().slice(0,5);let list=a.map(id=>prompts.find(p=>p.id===id)).filter(Boolean);return `<section class="page"><h2>🕐 Last 5 Viewed</h2><p class="muted">Your last five viewed posts are saved only in this browser.</p><div class="grid">${list.map(card).join('')||'<p class="muted">No history yet.</p>'}</div></section>`}
function profile(){return `<section class="page"><h2>👤 Profile</h2><div class="profile"><h3>${esc(user?.first_name||'Telegram User')}</h3><p class="muted">${user?.username?'@'+esc(user.username):'Telegram Connected ✓'}</p><p class="muted">Favorites: ${store.favorites().length} · History: ${store.history().length}</p></div><div class="sectionhead"><h3>Settings</h3></div><button class="btn secondary" onclick="clearData()">🧹 Clear Browser Data</button></section>`}
function render(){let content=route==='home'?home():route==='search'?searchPage():route==='favorites'?favorites():route==='history'?historyPage():route==='profile'?profile():details(route.split(':')[1]);app.innerHTML=`<div class="app">${header()}${content}${nav()}</div><div id="drawer" class="drawer" onclick="closeDrawer()"><aside class="drawerbox" onclick="event.stopPropagation()"><h2>AI Prompt Vault</h2><p class="muted">${esc(user?.first_name||'Telegram User')}</p><a href="#" onclick="go('home')">🏠 Home</a><a href="#" onclick="go('search')">🔍 Explore</a><a href="#" onclick="go('favorites')">❤️ Favorites</a><a href="#" onclick="go('history')">🕐 History</a><a href="#" onclick="go('profile')">👤 Profile</a><a href="#" onclick="go('home')">ℹ️ About</a></aside></div>`}
window.go=r=>{route=r;render();scrollTo(0,0)};window.openPrompt=id=>go('details:'+id);window.goBack=()=>go('home');window.filterCat=c=>{const s=document.querySelector('.chips');const left=s?s.scrollLeft:0;cat=c;query='';route='search';render();requestAnimationFrame(()=>{const n=document.querySelector('.chips');if(n)n.scrollLeft=left})};window.search=q=>{query=q;render()};window.openDrawer=()=>document.querySelector('#drawer')?.classList.add('open');window.closeDrawer=()=>document.querySelector('#drawer')?.classList.remove('open');
window.toggleFav=id=>{store.toggleFavorite(id);render()};window.copyPrompt=async id=>{let p=prompts.find(x=>x.id===id);await navigator.clipboard.writeText(p.prompt);alert('Prompt copied!')};window.downloadPrompt=id=>{let p=prompts.find(x=>x.id===id);let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([p.prompt],{type:'text/plain'}));a.download=p.id+'-prompt.txt';a.click();URL.revokeObjectURL(a.href)};
window.unlockPrompt=id=>{let ok=confirm('Demo rewarded-ad step: press OK to simulate the ad completion and unlock this prompt.');if(ok){store.unlock(id);render()}};
window.clearData=()=>{if(confirm('Clear Favorites, History and unlocked prompts from this browser?')){store.clear();render()}};
render();
window.addEventListener('scroll',()=>{if(window.scrollY+window.innerHeight>=document.documentElement.scrollHeight-160){let list=route==='search'?filteredSearch():(route==='home'?(cat==='All'?prompts:prompts.filter(p=>p.category.includes(cat))):[]);if(visibleCount<list.length)loadMore()}},{passive:true});
