// Add a new post by copying one object below and changing its fields.
// category MUST contain one or more names from `categories`.
// Example: category:['Girl','Cinematic','Realistic','Premium']
// The post will automatically appear in those category pages.
export const categories=['All','Boy','Girl','Premium','Thumbnail','Outfit','Filter','Cinematic','Realistic','Trending'];
export const prompts=[
{id:'p1',title:'Cinematic Girl Look',category:['Girl','Cinematic','Realistic'],rating:4.9,uses:'2.4K',premium:true,unlock:5,tags:['Girl','Cinematic','Portrait','4K'],image:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80',description:'Create a cinematic, realistic portrait with dramatic lighting and a polished editorial look.',prompt:'Create a cinematic realistic portrait of a confident young woman, dramatic soft rim light, natural skin texture, 85mm portrait lens, shallow depth of field, editorial color grading, ultra detailed, 4K.',youtube:'https://www.youtube.com/results?search_query=cinematic+ai+portrait+prompt'},
{id:'p2',title:'Cyberpunk Boy Portrait',category:['Boy','Cinematic','Realistic','Trending'],rating:4.8,uses:'1.8K',premium:false,unlock:0,tags:['Boy','Cyberpunk','Neon','4K'],image:'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80',description:'Neon cyberpunk portrait with cinematic atmosphere and realistic details.',prompt:'A cinematic cyberpunk male portrait in a neon city at night, realistic skin, reflective jacket, magenta and blue ambient light, volumetric fog, 35mm lens, shallow depth of field, highly detailed.',youtube:'https://www.youtube.com/results?search_query=cyberpunk+ai+portrait+prompt'},
{id:'p3',title:'Luxury Outfit Studio',category:['Girl','Outfit','Realistic'],rating:4.7,uses:'1.2K',premium:false,unlock:0,tags:['Luxury','Outfit','Studio','Realistic'],image:'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',description:'A premium fashion-studio concept for luxury outfit generations.',prompt:'High-end fashion editorial portrait, elegant luxury outfit, clean studio background, softbox lighting, realistic fabric texture, natural pose, professional fashion photography, crisp detail.',youtube:'https://www.youtube.com/results?search_query=AI+fashion+prompt+tutorial'},
{id:'p4',title:'4K Thumbnail Creator',category:['Thumbnail','Realistic','Trending','Premium'],rating:4.9,uses:'3.1K',premium:true,unlock:5,tags:['Thumbnail','YouTube','4K','Bold'],image:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80',description:'Generate bold, clean visual concepts suitable for modern video thumbnails.',prompt:'Create a high-impact YouTube thumbnail composition, bold focal subject, clean background, strong visual hierarchy, expressive face, crisp details, realistic lighting, 4K, professional creator aesthetic.',youtube:'https://www.youtube.com/results?search_query=AI+YouTube+thumbnail+prompt'}
];